spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summary?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: summary_user
    password: summary_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 운영에서는 validate or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
